# Site settings
title: Abramova Tatiana
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://tatianaab.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tatiana
user_description: While I enjoyed my previous work, I fell in love with learning to code. I have completed Full Stack Web Developer Bootcamp course and have hands on experience designing software applications, making configuration changes, writing codes to match needed functions and executing tests to ensure functionality.
I consider myself an innovator and I would love to work for an organization that’s leading the future of the industry.
Outside of coding, I love traveling, leading an active life and reading books. I enjoy outdoor activities such as camping, hiking, bike rides  and skiing.

user_title: Full Stuck Software Developer
email: abramovatatian@gmail.com
github_username:  https://github.com/TatianaAb
linkedin_username:  https://linkedin.com/tatiana-abramova-6807b778/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
